package main

// Tablas de páginas de códigos ESC/POS.
//
// Generadas a partir de los codecs estándar cp850 / cp858 / cp1252 / cp437.
// Sólo se listan los bytes 0x80–0xFF: el rango ASCII (0x00–0x7F) es idéntico en
// las cuatro tablas y se copia tal cual sin pasar por el mapa.

// codePageCP850 mapea runas Unicode a su byte en la página de códigos CP850.
var codePageCP850 = map[rune]byte{
	'Ç':    0x80, // U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA
	'ü':    0x81, // U+00FC LATIN SMALL LETTER U WITH DIAERESIS
	'é':    0x82, // U+00E9 LATIN SMALL LETTER E WITH ACUTE
	'â':    0x83, // U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
	'ä':    0x84, // U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
	'à':    0x85, // U+00E0 LATIN SMALL LETTER A WITH GRAVE
	'å':    0x86, // U+00E5 LATIN SMALL LETTER A WITH RING ABOVE
	'ç':    0x87, // U+00E7 LATIN SMALL LETTER C WITH CEDILLA
	'ê':    0x88, // U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
	'ë':    0x89, // U+00EB LATIN SMALL LETTER E WITH DIAERESIS
	'è':    0x8A, // U+00E8 LATIN SMALL LETTER E WITH GRAVE
	'ï':    0x8B, // U+00EF LATIN SMALL LETTER I WITH DIAERESIS
	'î':    0x8C, // U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
	'ì':    0x8D, // U+00EC LATIN SMALL LETTER I WITH GRAVE
	'Ä':    0x8E, // U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
	'Å':    0x8F, // U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
	'É':    0x90, // U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
	'æ':    0x91, // U+00E6 LATIN SMALL LETTER AE
	'Æ':    0x92, // U+00C6 LATIN CAPITAL LETTER AE
	'ô':    0x93, // U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
	'ö':    0x94, // U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
	'ò':    0x95, // U+00F2 LATIN SMALL LETTER O WITH GRAVE
	'û':    0x96, // U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
	'ù':    0x97, // U+00F9 LATIN SMALL LETTER U WITH GRAVE
	'ÿ':    0x98, // U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
	'Ö':    0x99, // U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
	'Ü':    0x9A, // U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
	'ø':    0x9B, // U+00F8 LATIN SMALL LETTER O WITH STROKE
	'£':    0x9C, // U+00A3 POUND SIGN
	'Ø':    0x9D, // U+00D8 LATIN CAPITAL LETTER O WITH STROKE
	'×':    0x9E, // U+00D7 MULTIPLICATION SIGN
	'ƒ':    0x9F, // U+0192 LATIN SMALL LETTER F WITH HOOK
	'á':    0xA0, // U+00E1 LATIN SMALL LETTER A WITH ACUTE
	'í':    0xA1, // U+00ED LATIN SMALL LETTER I WITH ACUTE
	'ó':    0xA2, // U+00F3 LATIN SMALL LETTER O WITH ACUTE
	'ú':    0xA3, // U+00FA LATIN SMALL LETTER U WITH ACUTE
	'ñ':    0xA4, // U+00F1 LATIN SMALL LETTER N WITH TILDE
	'Ñ':    0xA5, // U+00D1 LATIN CAPITAL LETTER N WITH TILDE
	'ª':    0xA6, // U+00AA FEMININE ORDINAL INDICATOR
	'º':    0xA7, // U+00BA MASCULINE ORDINAL INDICATOR
	'¿':    0xA8, // U+00BF INVERTED QUESTION MARK
	'®':    0xA9, // U+00AE REGISTERED SIGN
	'¬':    0xAA, // U+00AC NOT SIGN
	'½':    0xAB, // U+00BD VULGAR FRACTION ONE HALF
	'¼':    0xAC, // U+00BC VULGAR FRACTION ONE QUARTER
	'¡':    0xAD, // U+00A1 INVERTED EXCLAMATION MARK
	'«':    0xAE, // U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	'»':    0xAF, // U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	'░':    0xB0, // U+2591 LIGHT SHADE
	'▒':    0xB1, // U+2592 MEDIUM SHADE
	'▓':    0xB2, // U+2593 DARK SHADE
	'│':    0xB3, // U+2502 BOX DRAWINGS LIGHT VERTICAL
	'┤':    0xB4, // U+2524 BOX DRAWINGS LIGHT VERTICAL AND LEFT
	'Á':    0xB5, // U+00C1 LATIN CAPITAL LETTER A WITH ACUTE
	'Â':    0xB6, // U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	'À':    0xB7, // U+00C0 LATIN CAPITAL LETTER A WITH GRAVE
	'©':    0xB8, // U+00A9 COPYRIGHT SIGN
	'╣':    0xB9, // U+2563 BOX DRAWINGS DOUBLE VERTICAL AND LEFT
	'║':    0xBA, // U+2551 BOX DRAWINGS DOUBLE VERTICAL
	'╗':    0xBB, // U+2557 BOX DRAWINGS DOUBLE DOWN AND LEFT
	'╝':    0xBC, // U+255D BOX DRAWINGS DOUBLE UP AND LEFT
	'¢':    0xBD, // U+00A2 CENT SIGN
	'¥':    0xBE, // U+00A5 YEN SIGN
	'┐':    0xBF, // U+2510 BOX DRAWINGS LIGHT DOWN AND LEFT
	'└':    0xC0, // U+2514 BOX DRAWINGS LIGHT UP AND RIGHT
	'┴':    0xC1, // U+2534 BOX DRAWINGS LIGHT UP AND HORIZONTAL
	'┬':    0xC2, // U+252C BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
	'├':    0xC3, // U+251C BOX DRAWINGS LIGHT VERTICAL AND RIGHT
	'─':    0xC4, // U+2500 BOX DRAWINGS LIGHT HORIZONTAL
	'┼':    0xC5, // U+253C BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
	'ã':    0xC6, // U+00E3 LATIN SMALL LETTER A WITH TILDE
	'Ã':    0xC7, // U+00C3 LATIN CAPITAL LETTER A WITH TILDE
	'╚':    0xC8, // U+255A BOX DRAWINGS DOUBLE UP AND RIGHT
	'╔':    0xC9, // U+2554 BOX DRAWINGS DOUBLE DOWN AND RIGHT
	'╩':    0xCA, // U+2569 BOX DRAWINGS DOUBLE UP AND HORIZONTAL
	'╦':    0xCB, // U+2566 BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
	'╠':    0xCC, // U+2560 BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
	'═':    0xCD, // U+2550 BOX DRAWINGS DOUBLE HORIZONTAL
	'╬':    0xCE, // U+256C BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
	'¤':    0xCF, // U+00A4 CURRENCY SIGN
	'ð':    0xD0, // U+00F0 LATIN SMALL LETTER ETH
	'Ð':    0xD1, // U+00D0 LATIN CAPITAL LETTER ETH
	'Ê':    0xD2, // U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	'Ë':    0xD3, // U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
	'È':    0xD4, // U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
	'ı':    0xD5, // U+0131 LATIN SMALL LETTER DOTLESS I
	'Í':    0xD6, // U+00CD LATIN CAPITAL LETTER I WITH ACUTE
	'Î':    0xD7, // U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	'Ï':    0xD8, // U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS
	'┘':    0xD9, // U+2518 BOX DRAWINGS LIGHT UP AND LEFT
	'┌':    0xDA, // U+250C BOX DRAWINGS LIGHT DOWN AND RIGHT
	'█':    0xDB, // U+2588 FULL BLOCK
	'▄':    0xDC, // U+2584 LOWER HALF BLOCK
	'¦':    0xDD, // U+00A6 BROKEN BAR
	'Ì':    0xDE, // U+00CC LATIN CAPITAL LETTER I WITH GRAVE
	'▀':    0xDF, // U+2580 UPPER HALF BLOCK
	'Ó':    0xE0, // U+00D3 LATIN CAPITAL LETTER O WITH ACUTE
	'ß':    0xE1, // U+00DF LATIN SMALL LETTER SHARP S
	'Ô':    0xE2, // U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	'Ò':    0xE3, // U+00D2 LATIN CAPITAL LETTER O WITH GRAVE
	'õ':    0xE4, // U+00F5 LATIN SMALL LETTER O WITH TILDE
	'Õ':    0xE5, // U+00D5 LATIN CAPITAL LETTER O WITH TILDE
	'µ':    0xE6, // U+00B5 MICRO SIGN
	'þ':    0xE7, // U+00FE LATIN SMALL LETTER THORN
	'Þ':    0xE8, // U+00DE LATIN CAPITAL LETTER THORN
	'Ú':    0xE9, // U+00DA LATIN CAPITAL LETTER U WITH ACUTE
	'Û':    0xEA, // U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	'Ù':    0xEB, // U+00D9 LATIN CAPITAL LETTER U WITH GRAVE
	'ý':    0xEC, // U+00FD LATIN SMALL LETTER Y WITH ACUTE
	'Ý':    0xED, // U+00DD LATIN CAPITAL LETTER Y WITH ACUTE
	'¯':    0xEE, // U+00AF MACRON
	'´':    0xEF, // U+00B4 ACUTE ACCENT
	0x00AD: 0xF0, // U+00AD SOFT HYPHEN
	'±':    0xF1, // U+00B1 PLUS-MINUS SIGN
	'‗':    0xF2, // U+2017 DOUBLE LOW LINE
	'¾':    0xF3, // U+00BE VULGAR FRACTION THREE QUARTERS
	'¶':    0xF4, // U+00B6 PILCROW SIGN
	'§':    0xF5, // U+00A7 SECTION SIGN
	'÷':    0xF6, // U+00F7 DIVISION SIGN
	'¸':    0xF7, // U+00B8 CEDILLA
	'°':    0xF8, // U+00B0 DEGREE SIGN
	'¨':    0xF9, // U+00A8 DIAERESIS
	'·':    0xFA, // U+00B7 MIDDLE DOT
	'¹':    0xFB, // U+00B9 SUPERSCRIPT ONE
	'³':    0xFC, // U+00B3 SUPERSCRIPT THREE
	'²':    0xFD, // U+00B2 SUPERSCRIPT TWO
	'■':    0xFE, // U+25A0 BLACK SQUARE
	0x00A0: 0xFF, // U+00A0 NO-BREAK SPACE
}

// codePageCP858 mapea runas Unicode a su byte en la página de códigos CP858.
var codePageCP858 = map[rune]byte{
	'Ç':    0x80, // U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA
	'ü':    0x81, // U+00FC LATIN SMALL LETTER U WITH DIAERESIS
	'é':    0x82, // U+00E9 LATIN SMALL LETTER E WITH ACUTE
	'â':    0x83, // U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
	'ä':    0x84, // U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
	'à':    0x85, // U+00E0 LATIN SMALL LETTER A WITH GRAVE
	'å':    0x86, // U+00E5 LATIN SMALL LETTER A WITH RING ABOVE
	'ç':    0x87, // U+00E7 LATIN SMALL LETTER C WITH CEDILLA
	'ê':    0x88, // U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
	'ë':    0x89, // U+00EB LATIN SMALL LETTER E WITH DIAERESIS
	'è':    0x8A, // U+00E8 LATIN SMALL LETTER E WITH GRAVE
	'ï':    0x8B, // U+00EF LATIN SMALL LETTER I WITH DIAERESIS
	'î':    0x8C, // U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
	'ì':    0x8D, // U+00EC LATIN SMALL LETTER I WITH GRAVE
	'Ä':    0x8E, // U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
	'Å':    0x8F, // U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
	'É':    0x90, // U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
	'æ':    0x91, // U+00E6 LATIN SMALL LETTER AE
	'Æ':    0x92, // U+00C6 LATIN CAPITAL LETTER AE
	'ô':    0x93, // U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
	'ö':    0x94, // U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
	'ò':    0x95, // U+00F2 LATIN SMALL LETTER O WITH GRAVE
	'û':    0x96, // U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
	'ù':    0x97, // U+00F9 LATIN SMALL LETTER U WITH GRAVE
	'ÿ':    0x98, // U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
	'Ö':    0x99, // U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
	'Ü':    0x9A, // U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
	'ø':    0x9B, // U+00F8 LATIN SMALL LETTER O WITH STROKE
	'£':    0x9C, // U+00A3 POUND SIGN
	'Ø':    0x9D, // U+00D8 LATIN CAPITAL LETTER O WITH STROKE
	'×':    0x9E, // U+00D7 MULTIPLICATION SIGN
	'ƒ':    0x9F, // U+0192 LATIN SMALL LETTER F WITH HOOK
	'á':    0xA0, // U+00E1 LATIN SMALL LETTER A WITH ACUTE
	'í':    0xA1, // U+00ED LATIN SMALL LETTER I WITH ACUTE
	'ó':    0xA2, // U+00F3 LATIN SMALL LETTER O WITH ACUTE
	'ú':    0xA3, // U+00FA LATIN SMALL LETTER U WITH ACUTE
	'ñ':    0xA4, // U+00F1 LATIN SMALL LETTER N WITH TILDE
	'Ñ':    0xA5, // U+00D1 LATIN CAPITAL LETTER N WITH TILDE
	'ª':    0xA6, // U+00AA FEMININE ORDINAL INDICATOR
	'º':    0xA7, // U+00BA MASCULINE ORDINAL INDICATOR
	'¿':    0xA8, // U+00BF INVERTED QUESTION MARK
	'®':    0xA9, // U+00AE REGISTERED SIGN
	'¬':    0xAA, // U+00AC NOT SIGN
	'½':    0xAB, // U+00BD VULGAR FRACTION ONE HALF
	'¼':    0xAC, // U+00BC VULGAR FRACTION ONE QUARTER
	'¡':    0xAD, // U+00A1 INVERTED EXCLAMATION MARK
	'«':    0xAE, // U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	'»':    0xAF, // U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	'░':    0xB0, // U+2591 LIGHT SHADE
	'▒':    0xB1, // U+2592 MEDIUM SHADE
	'▓':    0xB2, // U+2593 DARK SHADE
	'│':    0xB3, // U+2502 BOX DRAWINGS LIGHT VERTICAL
	'┤':    0xB4, // U+2524 BOX DRAWINGS LIGHT VERTICAL AND LEFT
	'Á':    0xB5, // U+00C1 LATIN CAPITAL LETTER A WITH ACUTE
	'Â':    0xB6, // U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	'À':    0xB7, // U+00C0 LATIN CAPITAL LETTER A WITH GRAVE
	'©':    0xB8, // U+00A9 COPYRIGHT SIGN
	'╣':    0xB9, // U+2563 BOX DRAWINGS DOUBLE VERTICAL AND LEFT
	'║':    0xBA, // U+2551 BOX DRAWINGS DOUBLE VERTICAL
	'╗':    0xBB, // U+2557 BOX DRAWINGS DOUBLE DOWN AND LEFT
	'╝':    0xBC, // U+255D BOX DRAWINGS DOUBLE UP AND LEFT
	'¢':    0xBD, // U+00A2 CENT SIGN
	'¥':    0xBE, // U+00A5 YEN SIGN
	'┐':    0xBF, // U+2510 BOX DRAWINGS LIGHT DOWN AND LEFT
	'└':    0xC0, // U+2514 BOX DRAWINGS LIGHT UP AND RIGHT
	'┴':    0xC1, // U+2534 BOX DRAWINGS LIGHT UP AND HORIZONTAL
	'┬':    0xC2, // U+252C BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
	'├':    0xC3, // U+251C BOX DRAWINGS LIGHT VERTICAL AND RIGHT
	'─':    0xC4, // U+2500 BOX DRAWINGS LIGHT HORIZONTAL
	'┼':    0xC5, // U+253C BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
	'ã':    0xC6, // U+00E3 LATIN SMALL LETTER A WITH TILDE
	'Ã':    0xC7, // U+00C3 LATIN CAPITAL LETTER A WITH TILDE
	'╚':    0xC8, // U+255A BOX DRAWINGS DOUBLE UP AND RIGHT
	'╔':    0xC9, // U+2554 BOX DRAWINGS DOUBLE DOWN AND RIGHT
	'╩':    0xCA, // U+2569 BOX DRAWINGS DOUBLE UP AND HORIZONTAL
	'╦':    0xCB, // U+2566 BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
	'╠':    0xCC, // U+2560 BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
	'═':    0xCD, // U+2550 BOX DRAWINGS DOUBLE HORIZONTAL
	'╬':    0xCE, // U+256C BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
	'¤':    0xCF, // U+00A4 CURRENCY SIGN
	'ð':    0xD0, // U+00F0 LATIN SMALL LETTER ETH
	'Ð':    0xD1, // U+00D0 LATIN CAPITAL LETTER ETH
	'Ê':    0xD2, // U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	'Ë':    0xD3, // U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
	'È':    0xD4, // U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
	'€':    0xD5, // U+20AC EURO SIGN
	'Í':    0xD6, // U+00CD LATIN CAPITAL LETTER I WITH ACUTE
	'Î':    0xD7, // U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	'Ï':    0xD8, // U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS
	'┘':    0xD9, // U+2518 BOX DRAWINGS LIGHT UP AND LEFT
	'┌':    0xDA, // U+250C BOX DRAWINGS LIGHT DOWN AND RIGHT
	'█':    0xDB, // U+2588 FULL BLOCK
	'▄':    0xDC, // U+2584 LOWER HALF BLOCK
	'¦':    0xDD, // U+00A6 BROKEN BAR
	'Ì':    0xDE, // U+00CC LATIN CAPITAL LETTER I WITH GRAVE
	'▀':    0xDF, // U+2580 UPPER HALF BLOCK
	'Ó':    0xE0, // U+00D3 LATIN CAPITAL LETTER O WITH ACUTE
	'ß':    0xE1, // U+00DF LATIN SMALL LETTER SHARP S
	'Ô':    0xE2, // U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	'Ò':    0xE3, // U+00D2 LATIN CAPITAL LETTER O WITH GRAVE
	'õ':    0xE4, // U+00F5 LATIN SMALL LETTER O WITH TILDE
	'Õ':    0xE5, // U+00D5 LATIN CAPITAL LETTER O WITH TILDE
	'µ':    0xE6, // U+00B5 MICRO SIGN
	'þ':    0xE7, // U+00FE LATIN SMALL LETTER THORN
	'Þ':    0xE8, // U+00DE LATIN CAPITAL LETTER THORN
	'Ú':    0xE9, // U+00DA LATIN CAPITAL LETTER U WITH ACUTE
	'Û':    0xEA, // U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	'Ù':    0xEB, // U+00D9 LATIN CAPITAL LETTER U WITH GRAVE
	'ý':    0xEC, // U+00FD LATIN SMALL LETTER Y WITH ACUTE
	'Ý':    0xED, // U+00DD LATIN CAPITAL LETTER Y WITH ACUTE
	'¯':    0xEE, // U+00AF MACRON
	'´':    0xEF, // U+00B4 ACUTE ACCENT
	0x00AD: 0xF0, // U+00AD SOFT HYPHEN
	'±':    0xF1, // U+00B1 PLUS-MINUS SIGN
	'‗':    0xF2, // U+2017 DOUBLE LOW LINE
	'¾':    0xF3, // U+00BE VULGAR FRACTION THREE QUARTERS
	'¶':    0xF4, // U+00B6 PILCROW SIGN
	'§':    0xF5, // U+00A7 SECTION SIGN
	'÷':    0xF6, // U+00F7 DIVISION SIGN
	'¸':    0xF7, // U+00B8 CEDILLA
	'°':    0xF8, // U+00B0 DEGREE SIGN
	'¨':    0xF9, // U+00A8 DIAERESIS
	'·':    0xFA, // U+00B7 MIDDLE DOT
	'¹':    0xFB, // U+00B9 SUPERSCRIPT ONE
	'³':    0xFC, // U+00B3 SUPERSCRIPT THREE
	'²':    0xFD, // U+00B2 SUPERSCRIPT TWO
	'■':    0xFE, // U+25A0 BLACK SQUARE
	0x00A0: 0xFF, // U+00A0 NO-BREAK SPACE
}

// codePageCP1252 mapea runas Unicode a su byte en la página de códigos CP1252.
var codePageCP1252 = map[rune]byte{
	'€':    0x80, // U+20AC EURO SIGN
	'‚':    0x82, // U+201A SINGLE LOW-9 QUOTATION MARK
	'ƒ':    0x83, // U+0192 LATIN SMALL LETTER F WITH HOOK
	'„':    0x84, // U+201E DOUBLE LOW-9 QUOTATION MARK
	'…':    0x85, // U+2026 HORIZONTAL ELLIPSIS
	'†':    0x86, // U+2020 DAGGER
	'‡':    0x87, // U+2021 DOUBLE DAGGER
	'ˆ':    0x88, // U+02C6 MODIFIER LETTER CIRCUMFLEX ACCENT
	'‰':    0x89, // U+2030 PER MILLE SIGN
	'Š':    0x8A, // U+0160 LATIN CAPITAL LETTER S WITH CARON
	'‹':    0x8B, // U+2039 SINGLE LEFT-POINTING ANGLE QUOTATION MARK
	'Œ':    0x8C, // U+0152 LATIN CAPITAL LIGATURE OE
	'Ž':    0x8E, // U+017D LATIN CAPITAL LETTER Z WITH CARON
	'‘':    0x91, // U+2018 LEFT SINGLE QUOTATION MARK
	'’':    0x92, // U+2019 RIGHT SINGLE QUOTATION MARK
	'“':    0x93, // U+201C LEFT DOUBLE QUOTATION MARK
	'”':    0x94, // U+201D RIGHT DOUBLE QUOTATION MARK
	'•':    0x95, // U+2022 BULLET
	'–':    0x96, // U+2013 EN DASH
	'—':    0x97, // U+2014 EM DASH
	'˜':    0x98, // U+02DC SMALL TILDE
	'™':    0x99, // U+2122 TRADE MARK SIGN
	'š':    0x9A, // U+0161 LATIN SMALL LETTER S WITH CARON
	'›':    0x9B, // U+203A SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
	'œ':    0x9C, // U+0153 LATIN SMALL LIGATURE OE
	'ž':    0x9E, // U+017E LATIN SMALL LETTER Z WITH CARON
	'Ÿ':    0x9F, // U+0178 LATIN CAPITAL LETTER Y WITH DIAERESIS
	0x00A0: 0xA0, // U+00A0 NO-BREAK SPACE
	'¡':    0xA1, // U+00A1 INVERTED EXCLAMATION MARK
	'¢':    0xA2, // U+00A2 CENT SIGN
	'£':    0xA3, // U+00A3 POUND SIGN
	'¤':    0xA4, // U+00A4 CURRENCY SIGN
	'¥':    0xA5, // U+00A5 YEN SIGN
	'¦':    0xA6, // U+00A6 BROKEN BAR
	'§':    0xA7, // U+00A7 SECTION SIGN
	'¨':    0xA8, // U+00A8 DIAERESIS
	'©':    0xA9, // U+00A9 COPYRIGHT SIGN
	'ª':    0xAA, // U+00AA FEMININE ORDINAL INDICATOR
	'«':    0xAB, // U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	'¬':    0xAC, // U+00AC NOT SIGN
	0x00AD: 0xAD, // U+00AD SOFT HYPHEN
	'®':    0xAE, // U+00AE REGISTERED SIGN
	'¯':    0xAF, // U+00AF MACRON
	'°':    0xB0, // U+00B0 DEGREE SIGN
	'±':    0xB1, // U+00B1 PLUS-MINUS SIGN
	'²':    0xB2, // U+00B2 SUPERSCRIPT TWO
	'³':    0xB3, // U+00B3 SUPERSCRIPT THREE
	'´':    0xB4, // U+00B4 ACUTE ACCENT
	'µ':    0xB5, // U+00B5 MICRO SIGN
	'¶':    0xB6, // U+00B6 PILCROW SIGN
	'·':    0xB7, // U+00B7 MIDDLE DOT
	'¸':    0xB8, // U+00B8 CEDILLA
	'¹':    0xB9, // U+00B9 SUPERSCRIPT ONE
	'º':    0xBA, // U+00BA MASCULINE ORDINAL INDICATOR
	'»':    0xBB, // U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	'¼':    0xBC, // U+00BC VULGAR FRACTION ONE QUARTER
	'½':    0xBD, // U+00BD VULGAR FRACTION ONE HALF
	'¾':    0xBE, // U+00BE VULGAR FRACTION THREE QUARTERS
	'¿':    0xBF, // U+00BF INVERTED QUESTION MARK
	'À':    0xC0, // U+00C0 LATIN CAPITAL LETTER A WITH GRAVE
	'Á':    0xC1, // U+00C1 LATIN CAPITAL LETTER A WITH ACUTE
	'Â':    0xC2, // U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	'Ã':    0xC3, // U+00C3 LATIN CAPITAL LETTER A WITH TILDE
	'Ä':    0xC4, // U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
	'Å':    0xC5, // U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
	'Æ':    0xC6, // U+00C6 LATIN CAPITAL LETTER AE
	'Ç':    0xC7, // U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA
	'È':    0xC8, // U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
	'É':    0xC9, // U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
	'Ê':    0xCA, // U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	'Ë':    0xCB, // U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
	'Ì':    0xCC, // U+00CC LATIN CAPITAL LETTER I WITH GRAVE
	'Í':    0xCD, // U+00CD LATIN CAPITAL LETTER I WITH ACUTE
	'Î':    0xCE, // U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	'Ï':    0xCF, // U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS
	'Ð':    0xD0, // U+00D0 LATIN CAPITAL LETTER ETH
	'Ñ':    0xD1, // U+00D1 LATIN CAPITAL LETTER N WITH TILDE
	'Ò':    0xD2, // U+00D2 LATIN CAPITAL LETTER O WITH GRAVE
	'Ó':    0xD3, // U+00D3 LATIN CAPITAL LETTER O WITH ACUTE
	'Ô':    0xD4, // U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	'Õ':    0xD5, // U+00D5 LATIN CAPITAL LETTER O WITH TILDE
	'Ö':    0xD6, // U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
	'×':    0xD7, // U+00D7 MULTIPLICATION SIGN
	'Ø':    0xD8, // U+00D8 LATIN CAPITAL LETTER O WITH STROKE
	'Ù':    0xD9, // U+00D9 LATIN CAPITAL LETTER U WITH GRAVE
	'Ú':    0xDA, // U+00DA LATIN CAPITAL LETTER U WITH ACUTE
	'Û':    0xDB, // U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	'Ü':    0xDC, // U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
	'Ý':    0xDD, // U+00DD LATIN CAPITAL LETTER Y WITH ACUTE
	'Þ':    0xDE, // U+00DE LATIN CAPITAL LETTER THORN
	'ß':    0xDF, // U+00DF LATIN SMALL LETTER SHARP S
	'à':    0xE0, // U+00E0 LATIN SMALL LETTER A WITH GRAVE
	'á':    0xE1, // U+00E1 LATIN SMALL LETTER A WITH ACUTE
	'â':    0xE2, // U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
	'ã':    0xE3, // U+00E3 LATIN SMALL LETTER A WITH TILDE
	'ä':    0xE4, // U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
	'å':    0xE5, // U+00E5 LATIN SMALL LETTER A WITH RING ABOVE
	'æ':    0xE6, // U+00E6 LATIN SMALL LETTER AE
	'ç':    0xE7, // U+00E7 LATIN SMALL LETTER C WITH CEDILLA
	'è':    0xE8, // U+00E8 LATIN SMALL LETTER E WITH GRAVE
	'é':    0xE9, // U+00E9 LATIN SMALL LETTER E WITH ACUTE
	'ê':    0xEA, // U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
	'ë':    0xEB, // U+00EB LATIN SMALL LETTER E WITH DIAERESIS
	'ì':    0xEC, // U+00EC LATIN SMALL LETTER I WITH GRAVE
	'í':    0xED, // U+00ED LATIN SMALL LETTER I WITH ACUTE
	'î':    0xEE, // U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
	'ï':    0xEF, // U+00EF LATIN SMALL LETTER I WITH DIAERESIS
	'ð':    0xF0, // U+00F0 LATIN SMALL LETTER ETH
	'ñ':    0xF1, // U+00F1 LATIN SMALL LETTER N WITH TILDE
	'ò':    0xF2, // U+00F2 LATIN SMALL LETTER O WITH GRAVE
	'ó':    0xF3, // U+00F3 LATIN SMALL LETTER O WITH ACUTE
	'ô':    0xF4, // U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
	'õ':    0xF5, // U+00F5 LATIN SMALL LETTER O WITH TILDE
	'ö':    0xF6, // U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
	'÷':    0xF7, // U+00F7 DIVISION SIGN
	'ø':    0xF8, // U+00F8 LATIN SMALL LETTER O WITH STROKE
	'ù':    0xF9, // U+00F9 LATIN SMALL LETTER U WITH GRAVE
	'ú':    0xFA, // U+00FA LATIN SMALL LETTER U WITH ACUTE
	'û':    0xFB, // U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
	'ü':    0xFC, // U+00FC LATIN SMALL LETTER U WITH DIAERESIS
	'ý':    0xFD, // U+00FD LATIN SMALL LETTER Y WITH ACUTE
	'þ':    0xFE, // U+00FE LATIN SMALL LETTER THORN
	'ÿ':    0xFF, // U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
}

// codePageCP437 mapea runas Unicode a su byte en la página de códigos CP437.
var codePageCP437 = map[rune]byte{
	'Ç':    0x80, // U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA
	'ü':    0x81, // U+00FC LATIN SMALL LETTER U WITH DIAERESIS
	'é':    0x82, // U+00E9 LATIN SMALL LETTER E WITH ACUTE
	'â':    0x83, // U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
	'ä':    0x84, // U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
	'à':    0x85, // U+00E0 LATIN SMALL LETTER A WITH GRAVE
	'å':    0x86, // U+00E5 LATIN SMALL LETTER A WITH RING ABOVE
	'ç':    0x87, // U+00E7 LATIN SMALL LETTER C WITH CEDILLA
	'ê':    0x88, // U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
	'ë':    0x89, // U+00EB LATIN SMALL LETTER E WITH DIAERESIS
	'è':    0x8A, // U+00E8 LATIN SMALL LETTER E WITH GRAVE
	'ï':    0x8B, // U+00EF LATIN SMALL LETTER I WITH DIAERESIS
	'î':    0x8C, // U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
	'ì':    0x8D, // U+00EC LATIN SMALL LETTER I WITH GRAVE
	'Ä':    0x8E, // U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
	'Å':    0x8F, // U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
	'É':    0x90, // U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
	'æ':    0x91, // U+00E6 LATIN SMALL LETTER AE
	'Æ':    0x92, // U+00C6 LATIN CAPITAL LETTER AE
	'ô':    0x93, // U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
	'ö':    0x94, // U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
	'ò':    0x95, // U+00F2 LATIN SMALL LETTER O WITH GRAVE
	'û':    0x96, // U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
	'ù':    0x97, // U+00F9 LATIN SMALL LETTER U WITH GRAVE
	'ÿ':    0x98, // U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
	'Ö':    0x99, // U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
	'Ü':    0x9A, // U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
	'¢':    0x9B, // U+00A2 CENT SIGN
	'£':    0x9C, // U+00A3 POUND SIGN
	'¥':    0x9D, // U+00A5 YEN SIGN
	'₧':    0x9E, // U+20A7 PESETA SIGN
	'ƒ':    0x9F, // U+0192 LATIN SMALL LETTER F WITH HOOK
	'á':    0xA0, // U+00E1 LATIN SMALL LETTER A WITH ACUTE
	'í':    0xA1, // U+00ED LATIN SMALL LETTER I WITH ACUTE
	'ó':    0xA2, // U+00F3 LATIN SMALL LETTER O WITH ACUTE
	'ú':    0xA3, // U+00FA LATIN SMALL LETTER U WITH ACUTE
	'ñ':    0xA4, // U+00F1 LATIN SMALL LETTER N WITH TILDE
	'Ñ':    0xA5, // U+00D1 LATIN CAPITAL LETTER N WITH TILDE
	'ª':    0xA6, // U+00AA FEMININE ORDINAL INDICATOR
	'º':    0xA7, // U+00BA MASCULINE ORDINAL INDICATOR
	'¿':    0xA8, // U+00BF INVERTED QUESTION MARK
	'⌐':    0xA9, // U+2310 REVERSED NOT SIGN
	'¬':    0xAA, // U+00AC NOT SIGN
	'½':    0xAB, // U+00BD VULGAR FRACTION ONE HALF
	'¼':    0xAC, // U+00BC VULGAR FRACTION ONE QUARTER
	'¡':    0xAD, // U+00A1 INVERTED EXCLAMATION MARK
	'«':    0xAE, // U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	'»':    0xAF, // U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	'░':    0xB0, // U+2591 LIGHT SHADE
	'▒':    0xB1, // U+2592 MEDIUM SHADE
	'▓':    0xB2, // U+2593 DARK SHADE
	'│':    0xB3, // U+2502 BOX DRAWINGS LIGHT VERTICAL
	'┤':    0xB4, // U+2524 BOX DRAWINGS LIGHT VERTICAL AND LEFT
	'╡':    0xB5, // U+2561 BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
	'╢':    0xB6, // U+2562 BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
	'╖':    0xB7, // U+2556 BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
	'╕':    0xB8, // U+2555 BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
	'╣':    0xB9, // U+2563 BOX DRAWINGS DOUBLE VERTICAL AND LEFT
	'║':    0xBA, // U+2551 BOX DRAWINGS DOUBLE VERTICAL
	'╗':    0xBB, // U+2557 BOX DRAWINGS DOUBLE DOWN AND LEFT
	'╝':    0xBC, // U+255D BOX DRAWINGS DOUBLE UP AND LEFT
	'╜':    0xBD, // U+255C BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
	'╛':    0xBE, // U+255B BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
	'┐':    0xBF, // U+2510 BOX DRAWINGS LIGHT DOWN AND LEFT
	'└':    0xC0, // U+2514 BOX DRAWINGS LIGHT UP AND RIGHT
	'┴':    0xC1, // U+2534 BOX DRAWINGS LIGHT UP AND HORIZONTAL
	'┬':    0xC2, // U+252C BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
	'├':    0xC3, // U+251C BOX DRAWINGS LIGHT VERTICAL AND RIGHT
	'─':    0xC4, // U+2500 BOX DRAWINGS LIGHT HORIZONTAL
	'┼':    0xC5, // U+253C BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
	'╞':    0xC6, // U+255E BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
	'╟':    0xC7, // U+255F BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
	'╚':    0xC8, // U+255A BOX DRAWINGS DOUBLE UP AND RIGHT
	'╔':    0xC9, // U+2554 BOX DRAWINGS DOUBLE DOWN AND RIGHT
	'╩':    0xCA, // U+2569 BOX DRAWINGS DOUBLE UP AND HORIZONTAL
	'╦':    0xCB, // U+2566 BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
	'╠':    0xCC, // U+2560 BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
	'═':    0xCD, // U+2550 BOX DRAWINGS DOUBLE HORIZONTAL
	'╬':    0xCE, // U+256C BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
	'╧':    0xCF, // U+2567 BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
	'╨':    0xD0, // U+2568 BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
	'╤':    0xD1, // U+2564 BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
	'╥':    0xD2, // U+2565 BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
	'╙':    0xD3, // U+2559 BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
	'╘':    0xD4, // U+2558 BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
	'╒':    0xD5, // U+2552 BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
	'╓':    0xD6, // U+2553 BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
	'╫':    0xD7, // U+256B BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
	'╪':    0xD8, // U+256A BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
	'┘':    0xD9, // U+2518 BOX DRAWINGS LIGHT UP AND LEFT
	'┌':    0xDA, // U+250C BOX DRAWINGS LIGHT DOWN AND RIGHT
	'█':    0xDB, // U+2588 FULL BLOCK
	'▄':    0xDC, // U+2584 LOWER HALF BLOCK
	'▌':    0xDD, // U+258C LEFT HALF BLOCK
	'▐':    0xDE, // U+2590 RIGHT HALF BLOCK
	'▀':    0xDF, // U+2580 UPPER HALF BLOCK
	'α':    0xE0, // U+03B1 GREEK SMALL LETTER ALPHA
	'ß':    0xE1, // U+00DF LATIN SMALL LETTER SHARP S
	'Γ':    0xE2, // U+0393 GREEK CAPITAL LETTER GAMMA
	'π':    0xE3, // U+03C0 GREEK SMALL LETTER PI
	'Σ':    0xE4, // U+03A3 GREEK CAPITAL LETTER SIGMA
	'σ':    0xE5, // U+03C3 GREEK SMALL LETTER SIGMA
	'µ':    0xE6, // U+00B5 MICRO SIGN
	'τ':    0xE7, // U+03C4 GREEK SMALL LETTER TAU
	'Φ':    0xE8, // U+03A6 GREEK CAPITAL LETTER PHI
	'Θ':    0xE9, // U+0398 GREEK CAPITAL LETTER THETA
	'Ω':    0xEA, // U+03A9 GREEK CAPITAL LETTER OMEGA
	'δ':    0xEB, // U+03B4 GREEK SMALL LETTER DELTA
	'∞':    0xEC, // U+221E INFINITY
	'φ':    0xED, // U+03C6 GREEK SMALL LETTER PHI
	'ε':    0xEE, // U+03B5 GREEK SMALL LETTER EPSILON
	'∩':    0xEF, // U+2229 INTERSECTION
	'≡':    0xF0, // U+2261 IDENTICAL TO
	'±':    0xF1, // U+00B1 PLUS-MINUS SIGN
	'≥':    0xF2, // U+2265 GREATER-THAN OR EQUAL TO
	'≤':    0xF3, // U+2264 LESS-THAN OR EQUAL TO
	'⌠':    0xF4, // U+2320 TOP HALF INTEGRAL
	'⌡':    0xF5, // U+2321 BOTTOM HALF INTEGRAL
	'÷':    0xF6, // U+00F7 DIVISION SIGN
	'≈':    0xF7, // U+2248 ALMOST EQUAL TO
	'°':    0xF8, // U+00B0 DEGREE SIGN
	'∙':    0xF9, // U+2219 BULLET OPERATOR
	'·':    0xFA, // U+00B7 MIDDLE DOT
	'√':    0xFB, // U+221A SQUARE ROOT
	'ⁿ':    0xFC, // U+207F SUPERSCRIPT LATIN SMALL LETTER N
	'²':    0xFD, // U+00B2 SUPERSCRIPT TWO
	'■':    0xFE, // U+25A0 BLACK SQUARE
	0x00A0: 0xFF, // U+00A0 NO-BREAK SPACE
}

// asciiFallback traduce runas sin representación en la página de códigos activa
// a su equivalente ASCII más cercano, para que el ticket nunca imprima basura.
var asciiFallback = map[rune]string{
	0x00A0: " ",   // U+00A0 NO-BREAK SPACE
	'¨':    " ",   // U+00A8 DIAERESIS
	'ª':    "a",   // U+00AA FEMININE ORDINAL INDICATOR
	'«':    "<<",  // U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	'¯':    " ",   // U+00AF MACRON
	'²':    "2",   // U+00B2 SUPERSCRIPT TWO
	'³':    "3",   // U+00B3 SUPERSCRIPT THREE
	'´':    " ",   // U+00B4 ACUTE ACCENT
	'·':    ".",   // U+00B7 MIDDLE DOT
	'¸':    " ",   // U+00B8 CEDILLA
	'¹':    "1",   // U+00B9 SUPERSCRIPT ONE
	'º':    "o",   // U+00BA MASCULINE ORDINAL INDICATOR
	'»':    ">>",  // U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	'¼':    "14",  // U+00BC VULGAR FRACTION ONE QUARTER
	'½':    "12",  // U+00BD VULGAR FRACTION ONE HALF
	'¾':    "34",  // U+00BE VULGAR FRACTION THREE QUARTERS
	'À':    "A",   // U+00C0 LATIN CAPITAL LETTER A WITH GRAVE
	'Á':    "A",   // U+00C1 LATIN CAPITAL LETTER A WITH ACUTE
	'Â':    "A",   // U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	'Ã':    "A",   // U+00C3 LATIN CAPITAL LETTER A WITH TILDE
	'Ä':    "A",   // U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
	'Å':    "A",   // U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
	'Æ':    "AE",  // U+00C6 LATIN CAPITAL LETTER AE
	'Ç':    "C",   // U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA
	'È':    "E",   // U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
	'É':    "E",   // U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
	'Ê':    "E",   // U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	'Ë':    "E",   // U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
	'Ì':    "I",   // U+00CC LATIN CAPITAL LETTER I WITH GRAVE
	'Í':    "I",   // U+00CD LATIN CAPITAL LETTER I WITH ACUTE
	'Î':    "I",   // U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	'Ï':    "I",   // U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS
	'Ð':    "D",   // U+00D0 LATIN CAPITAL LETTER ETH
	'Ñ':    "N",   // U+00D1 LATIN CAPITAL LETTER N WITH TILDE
	'Ò':    "O",   // U+00D2 LATIN CAPITAL LETTER O WITH GRAVE
	'Ó':    "O",   // U+00D3 LATIN CAPITAL LETTER O WITH ACUTE
	'Ô':    "O",   // U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	'Õ':    "O",   // U+00D5 LATIN CAPITAL LETTER O WITH TILDE
	'Ö':    "O",   // U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
	'Ø':    "O",   // U+00D8 LATIN CAPITAL LETTER O WITH STROKE
	'Ù':    "U",   // U+00D9 LATIN CAPITAL LETTER U WITH GRAVE
	'Ú':    "U",   // U+00DA LATIN CAPITAL LETTER U WITH ACUTE
	'Û':    "U",   // U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	'Ü':    "U",   // U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
	'Ý':    "Y",   // U+00DD LATIN CAPITAL LETTER Y WITH ACUTE
	'Þ':    "TH",  // U+00DE LATIN CAPITAL LETTER THORN
	'ß':    "ss",  // U+00DF LATIN SMALL LETTER SHARP S
	'à':    "a",   // U+00E0 LATIN SMALL LETTER A WITH GRAVE
	'á':    "a",   // U+00E1 LATIN SMALL LETTER A WITH ACUTE
	'â':    "a",   // U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
	'ã':    "a",   // U+00E3 LATIN SMALL LETTER A WITH TILDE
	'ä':    "a",   // U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
	'å':    "a",   // U+00E5 LATIN SMALL LETTER A WITH RING ABOVE
	'æ':    "ae",  // U+00E6 LATIN SMALL LETTER AE
	'ç':    "c",   // U+00E7 LATIN SMALL LETTER C WITH CEDILLA
	'è':    "e",   // U+00E8 LATIN SMALL LETTER E WITH GRAVE
	'é':    "e",   // U+00E9 LATIN SMALL LETTER E WITH ACUTE
	'ê':    "e",   // U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
	'ë':    "e",   // U+00EB LATIN SMALL LETTER E WITH DIAERESIS
	'ì':    "i",   // U+00EC LATIN SMALL LETTER I WITH GRAVE
	'í':    "i",   // U+00ED LATIN SMALL LETTER I WITH ACUTE
	'î':    "i",   // U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
	'ï':    "i",   // U+00EF LATIN SMALL LETTER I WITH DIAERESIS
	'ð':    "d",   // U+00F0 LATIN SMALL LETTER ETH
	'ñ':    "n",   // U+00F1 LATIN SMALL LETTER N WITH TILDE
	'ò':    "o",   // U+00F2 LATIN SMALL LETTER O WITH GRAVE
	'ó':    "o",   // U+00F3 LATIN SMALL LETTER O WITH ACUTE
	'ô':    "o",   // U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
	'õ':    "o",   // U+00F5 LATIN SMALL LETTER O WITH TILDE
	'ö':    "o",   // U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
	'ø':    "o",   // U+00F8 LATIN SMALL LETTER O WITH STROKE
	'ù':    "u",   // U+00F9 LATIN SMALL LETTER U WITH GRAVE
	'ú':    "u",   // U+00FA LATIN SMALL LETTER U WITH ACUTE
	'û':    "u",   // U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
	'ü':    "u",   // U+00FC LATIN SMALL LETTER U WITH DIAERESIS
	'ý':    "y",   // U+00FD LATIN SMALL LETTER Y WITH ACUTE
	'þ':    "th",  // U+00FE LATIN SMALL LETTER THORN
	'ÿ':    "y",   // U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
	'Ā':    "A",   // U+0100 LATIN CAPITAL LETTER A WITH MACRON
	'ā':    "a",   // U+0101 LATIN SMALL LETTER A WITH MACRON
	'Ă':    "A",   // U+0102 LATIN CAPITAL LETTER A WITH BREVE
	'ă':    "a",   // U+0103 LATIN SMALL LETTER A WITH BREVE
	'Ą':    "A",   // U+0104 LATIN CAPITAL LETTER A WITH OGONEK
	'ą':    "a",   // U+0105 LATIN SMALL LETTER A WITH OGONEK
	'Ć':    "C",   // U+0106 LATIN CAPITAL LETTER C WITH ACUTE
	'ć':    "c",   // U+0107 LATIN SMALL LETTER C WITH ACUTE
	'Ĉ':    "C",   // U+0108 LATIN CAPITAL LETTER C WITH CIRCUMFLEX
	'ĉ':    "c",   // U+0109 LATIN SMALL LETTER C WITH CIRCUMFLEX
	'Ċ':    "C",   // U+010A LATIN CAPITAL LETTER C WITH DOT ABOVE
	'ċ':    "c",   // U+010B LATIN SMALL LETTER C WITH DOT ABOVE
	'Č':    "C",   // U+010C LATIN CAPITAL LETTER C WITH CARON
	'č':    "c",   // U+010D LATIN SMALL LETTER C WITH CARON
	'Ď':    "D",   // U+010E LATIN CAPITAL LETTER D WITH CARON
	'ď':    "d",   // U+010F LATIN SMALL LETTER D WITH CARON
	'Đ':    "D",   // U+0110 LATIN CAPITAL LETTER D WITH STROKE
	'đ':    "d",   // U+0111 LATIN SMALL LETTER D WITH STROKE
	'Ē':    "E",   // U+0112 LATIN CAPITAL LETTER E WITH MACRON
	'ē':    "e",   // U+0113 LATIN SMALL LETTER E WITH MACRON
	'Ĕ':    "E",   // U+0114 LATIN CAPITAL LETTER E WITH BREVE
	'ĕ':    "e",   // U+0115 LATIN SMALL LETTER E WITH BREVE
	'Ė':    "E",   // U+0116 LATIN CAPITAL LETTER E WITH DOT ABOVE
	'ė':    "e",   // U+0117 LATIN SMALL LETTER E WITH DOT ABOVE
	'Ę':    "E",   // U+0118 LATIN CAPITAL LETTER E WITH OGONEK
	'ę':    "e",   // U+0119 LATIN SMALL LETTER E WITH OGONEK
	'Ě':    "E",   // U+011A LATIN CAPITAL LETTER E WITH CARON
	'ě':    "e",   // U+011B LATIN SMALL LETTER E WITH CARON
	'Ĝ':    "G",   // U+011C LATIN CAPITAL LETTER G WITH CIRCUMFLEX
	'ĝ':    "g",   // U+011D LATIN SMALL LETTER G WITH CIRCUMFLEX
	'Ğ':    "G",   // U+011E LATIN CAPITAL LETTER G WITH BREVE
	'ğ':    "g",   // U+011F LATIN SMALL LETTER G WITH BREVE
	'Ġ':    "G",   // U+0120 LATIN CAPITAL LETTER G WITH DOT ABOVE
	'ġ':    "g",   // U+0121 LATIN SMALL LETTER G WITH DOT ABOVE
	'Ģ':    "G",   // U+0122 LATIN CAPITAL LETTER G WITH CEDILLA
	'ģ':    "g",   // U+0123 LATIN SMALL LETTER G WITH CEDILLA
	'Ĥ':    "H",   // U+0124 LATIN CAPITAL LETTER H WITH CIRCUMFLEX
	'ĥ':    "h",   // U+0125 LATIN SMALL LETTER H WITH CIRCUMFLEX
	'Ĩ':    "I",   // U+0128 LATIN CAPITAL LETTER I WITH TILDE
	'ĩ':    "i",   // U+0129 LATIN SMALL LETTER I WITH TILDE
	'Ī':    "I",   // U+012A LATIN CAPITAL LETTER I WITH MACRON
	'ī':    "i",   // U+012B LATIN SMALL LETTER I WITH MACRON
	'Ĭ':    "I",   // U+012C LATIN CAPITAL LETTER I WITH BREVE
	'ĭ':    "i",   // U+012D LATIN SMALL LETTER I WITH BREVE
	'Į':    "I",   // U+012E LATIN CAPITAL LETTER I WITH OGONEK
	'į':    "i",   // U+012F LATIN SMALL LETTER I WITH OGONEK
	'İ':    "I",   // U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE
	'Ĳ':    "IJ",  // U+0132 LATIN CAPITAL LIGATURE IJ
	'ĳ':    "ij",  // U+0133 LATIN SMALL LIGATURE IJ
	'Ĵ':    "J",   // U+0134 LATIN CAPITAL LETTER J WITH CIRCUMFLEX
	'ĵ':    "j",   // U+0135 LATIN SMALL LETTER J WITH CIRCUMFLEX
	'Ķ':    "K",   // U+0136 LATIN CAPITAL LETTER K WITH CEDILLA
	'ķ':    "k",   // U+0137 LATIN SMALL LETTER K WITH CEDILLA
	'Ĺ':    "L",   // U+0139 LATIN CAPITAL LETTER L WITH ACUTE
	'ĺ':    "l",   // U+013A LATIN SMALL LETTER L WITH ACUTE
	'Ļ':    "L",   // U+013B LATIN CAPITAL LETTER L WITH CEDILLA
	'ļ':    "l",   // U+013C LATIN SMALL LETTER L WITH CEDILLA
	'Ľ':    "L",   // U+013D LATIN CAPITAL LETTER L WITH CARON
	'ľ':    "l",   // U+013E LATIN SMALL LETTER L WITH CARON
	'Ŀ':    "L",   // U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT
	'ŀ':    "l",   // U+0140 LATIN SMALL LETTER L WITH MIDDLE DOT
	'Ń':    "N",   // U+0143 LATIN CAPITAL LETTER N WITH ACUTE
	'ń':    "n",   // U+0144 LATIN SMALL LETTER N WITH ACUTE
	'Ņ':    "N",   // U+0145 LATIN CAPITAL LETTER N WITH CEDILLA
	'ņ':    "n",   // U+0146 LATIN SMALL LETTER N WITH CEDILLA
	'Ň':    "N",   // U+0147 LATIN CAPITAL LETTER N WITH CARON
	'ň':    "n",   // U+0148 LATIN SMALL LETTER N WITH CARON
	'ŉ':    "n",   // U+0149 LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
	'Ō':    "O",   // U+014C LATIN CAPITAL LETTER O WITH MACRON
	'ō':    "o",   // U+014D LATIN SMALL LETTER O WITH MACRON
	'Ŏ':    "O",   // U+014E LATIN CAPITAL LETTER O WITH BREVE
	'ŏ':    "o",   // U+014F LATIN SMALL LETTER O WITH BREVE
	'Ő':    "O",   // U+0150 LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
	'ő':    "o",   // U+0151 LATIN SMALL LETTER O WITH DOUBLE ACUTE
	'Ŕ':    "R",   // U+0154 LATIN CAPITAL LETTER R WITH ACUTE
	'ŕ':    "r",   // U+0155 LATIN SMALL LETTER R WITH ACUTE
	'Ŗ':    "R",   // U+0156 LATIN CAPITAL LETTER R WITH CEDILLA
	'ŗ':    "r",   // U+0157 LATIN SMALL LETTER R WITH CEDILLA
	'Ř':    "R",   // U+0158 LATIN CAPITAL LETTER R WITH CARON
	'ř':    "r",   // U+0159 LATIN SMALL LETTER R WITH CARON
	'Ś':    "S",   // U+015A LATIN CAPITAL LETTER S WITH ACUTE
	'ś':    "s",   // U+015B LATIN SMALL LETTER S WITH ACUTE
	'Ŝ':    "S",   // U+015C LATIN CAPITAL LETTER S WITH CIRCUMFLEX
	'ŝ':    "s",   // U+015D LATIN SMALL LETTER S WITH CIRCUMFLEX
	'Ş':    "S",   // U+015E LATIN CAPITAL LETTER S WITH CEDILLA
	'ş':    "s",   // U+015F LATIN SMALL LETTER S WITH CEDILLA
	'Š':    "S",   // U+0160 LATIN CAPITAL LETTER S WITH CARON
	'š':    "s",   // U+0161 LATIN SMALL LETTER S WITH CARON
	'Ţ':    "T",   // U+0162 LATIN CAPITAL LETTER T WITH CEDILLA
	'ţ':    "t",   // U+0163 LATIN SMALL LETTER T WITH CEDILLA
	'Ť':    "T",   // U+0164 LATIN CAPITAL LETTER T WITH CARON
	'ť':    "t",   // U+0165 LATIN SMALL LETTER T WITH CARON
	'Ũ':    "U",   // U+0168 LATIN CAPITAL LETTER U WITH TILDE
	'ũ':    "u",   // U+0169 LATIN SMALL LETTER U WITH TILDE
	'Ū':    "U",   // U+016A LATIN CAPITAL LETTER U WITH MACRON
	'ū':    "u",   // U+016B LATIN SMALL LETTER U WITH MACRON
	'Ŭ':    "U",   // U+016C LATIN CAPITAL LETTER U WITH BREVE
	'ŭ':    "u",   // U+016D LATIN SMALL LETTER U WITH BREVE
	'Ů':    "U",   // U+016E LATIN CAPITAL LETTER U WITH RING ABOVE
	'ů':    "u",   // U+016F LATIN SMALL LETTER U WITH RING ABOVE
	'Ű':    "U",   // U+0170 LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
	'ű':    "u",   // U+0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE
	'Ų':    "U",   // U+0172 LATIN CAPITAL LETTER U WITH OGONEK
	'ų':    "u",   // U+0173 LATIN SMALL LETTER U WITH OGONEK
	'Ŵ':    "W",   // U+0174 LATIN CAPITAL LETTER W WITH CIRCUMFLEX
	'ŵ':    "w",   // U+0175 LATIN SMALL LETTER W WITH CIRCUMFLEX
	'Ŷ':    "Y",   // U+0176 LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
	'ŷ':    "y",   // U+0177 LATIN SMALL LETTER Y WITH CIRCUMFLEX
	'Ÿ':    "Y",   // U+0178 LATIN CAPITAL LETTER Y WITH DIAERESIS
	'Ź':    "Z",   // U+0179 LATIN CAPITAL LETTER Z WITH ACUTE
	'ź':    "z",   // U+017A LATIN SMALL LETTER Z WITH ACUTE
	'Ż':    "Z",   // U+017B LATIN CAPITAL LETTER Z WITH DOT ABOVE
	'ż':    "z",   // U+017C LATIN SMALL LETTER Z WITH DOT ABOVE
	'Ž':    "Z",   // U+017D LATIN CAPITAL LETTER Z WITH CARON
	'ž':    "z",   // U+017E LATIN SMALL LETTER Z WITH CARON
	'ſ':    "s",   // U+017F LATIN SMALL LETTER LONG S
	'Ơ':    "O",   // U+01A0 LATIN CAPITAL LETTER O WITH HORN
	'ơ':    "o",   // U+01A1 LATIN SMALL LETTER O WITH HORN
	'Ư':    "U",   // U+01AF LATIN CAPITAL LETTER U WITH HORN
	'ư':    "u",   // U+01B0 LATIN SMALL LETTER U WITH HORN
	'Ǆ':    "DZ",  // U+01C4 LATIN CAPITAL LETTER DZ WITH CARON
	'ǅ':    "Dz",  // U+01C5 LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
	'ǆ':    "dz",  // U+01C6 LATIN SMALL LETTER DZ WITH CARON
	'Ǉ':    "LJ",  // U+01C7 LATIN CAPITAL LETTER LJ
	'ǈ':    "Lj",  // U+01C8 LATIN CAPITAL LETTER L WITH SMALL LETTER J
	'ǉ':    "lj",  // U+01C9 LATIN SMALL LETTER LJ
	'Ǌ':    "NJ",  // U+01CA LATIN CAPITAL LETTER NJ
	'ǋ':    "Nj",  // U+01CB LATIN CAPITAL LETTER N WITH SMALL LETTER J
	'ǌ':    "nj",  // U+01CC LATIN SMALL LETTER NJ
	'Ǎ':    "A",   // U+01CD LATIN CAPITAL LETTER A WITH CARON
	'ǎ':    "a",   // U+01CE LATIN SMALL LETTER A WITH CARON
	'Ǐ':    "I",   // U+01CF LATIN CAPITAL LETTER I WITH CARON
	'ǐ':    "i",   // U+01D0 LATIN SMALL LETTER I WITH CARON
	'Ǒ':    "O",   // U+01D1 LATIN CAPITAL LETTER O WITH CARON
	'ǒ':    "o",   // U+01D2 LATIN SMALL LETTER O WITH CARON
	'Ǔ':    "U",   // U+01D3 LATIN CAPITAL LETTER U WITH CARON
	'ǔ':    "u",   // U+01D4 LATIN SMALL LETTER U WITH CARON
	'Ǖ':    "U",   // U+01D5 LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
	'ǖ':    "u",   // U+01D6 LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
	'Ǘ':    "U",   // U+01D7 LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
	'ǘ':    "u",   // U+01D8 LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
	'Ǚ':    "U",   // U+01D9 LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
	'ǚ':    "u",   // U+01DA LATIN SMALL LETTER U WITH DIAERESIS AND CARON
	'Ǜ':    "U",   // U+01DB LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
	'ǜ':    "u",   // U+01DC LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
	'Ǟ':    "A",   // U+01DE LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
	'ǟ':    "a",   // U+01DF LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
	'Ǡ':    "A",   // U+01E0 LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
	'ǡ':    "a",   // U+01E1 LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
	'Ǧ':    "G",   // U+01E6 LATIN CAPITAL LETTER G WITH CARON
	'ǧ':    "g",   // U+01E7 LATIN SMALL LETTER G WITH CARON
	'Ǩ':    "K",   // U+01E8 LATIN CAPITAL LETTER K WITH CARON
	'ǩ':    "k",   // U+01E9 LATIN SMALL LETTER K WITH CARON
	'Ǫ':    "O",   // U+01EA LATIN CAPITAL LETTER O WITH OGONEK
	'ǫ':    "o",   // U+01EB LATIN SMALL LETTER O WITH OGONEK
	'Ǭ':    "O",   // U+01EC LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
	'ǭ':    "o",   // U+01ED LATIN SMALL LETTER O WITH OGONEK AND MACRON
	'ǰ':    "j",   // U+01F0 LATIN SMALL LETTER J WITH CARON
	'Ǳ':    "DZ",  // U+01F1 LATIN CAPITAL LETTER DZ
	'ǲ':    "Dz",  // U+01F2 LATIN CAPITAL LETTER D WITH SMALL LETTER Z
	'ǳ':    "dz",  // U+01F3 LATIN SMALL LETTER DZ
	'Ǵ':    "G",   // U+01F4 LATIN CAPITAL LETTER G WITH ACUTE
	'ǵ':    "g",   // U+01F5 LATIN SMALL LETTER G WITH ACUTE
	'Ǹ':    "N",   // U+01F8 LATIN CAPITAL LETTER N WITH GRAVE
	'ǹ':    "n",   // U+01F9 LATIN SMALL LETTER N WITH GRAVE
	'Ǻ':    "A",   // U+01FA LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
	'ǻ':    "a",   // U+01FB LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
	'‐':    "-",   // U+2010 HYPHEN
	'‑':    "-",   // U+2011 NON-BREAKING HYPHEN
	'‒':    "-",   // U+2012 FIGURE DASH
	'–':    "-",   // U+2013 EN DASH
	'—':    "-",   // U+2014 EM DASH
	'―':    "-",   // U+2015 HORIZONTAL BAR
	'‘':    "'",   // U+2018 LEFT SINGLE QUOTATION MARK
	'’':    "'",   // U+2019 RIGHT SINGLE QUOTATION MARK
	'‚':    "'",   // U+201A SINGLE LOW-9 QUOTATION MARK
	'“':    "\"",  // U+201C LEFT DOUBLE QUOTATION MARK
	'”':    "\"",  // U+201D RIGHT DOUBLE QUOTATION MARK
	'„':    "\"",  // U+201E DOUBLE LOW-9 QUOTATION MARK
	'•':    "*",   // U+2022 BULLET
	'…':    "...", // U+2026 HORIZONTAL ELLIPSIS
	'‰':    "%",   // U+2030 PER MILLE SIGN
	'‹':    "<",   // U+2039 SINGLE LEFT-POINTING ANGLE QUOTATION MARK
	'›':    ">",   // U+203A SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
	'€':    "EUR", // U+20AC EURO SIGN
	'™':    "TM",  // U+2122 TRADE MARK SIGN
}
